Historic script and css
vch9/PresidentJS pull request #12
Opened 2020-05-17 11:38 UTC by vch9

The historic is a regular table, scrollable if we have to much rows.

We might change the background-colors.

![president](https://user-images.githubusercontent.com/32700018/82143335-63093500-9843-11ea-8557-86c354c9a05e.png)

2020-05-17 15:17 UTC, vch9 commented
Tried in Firefox and Chrome

2020-05-22 22:33 UTC, maiste requested changes
It works for me on Chrome and Firefox. Can you just change the color symbol with unicode char ?

2020-05-23 18:31 UTC, vch9 commented
> Can you just change the color symbol with unicode char ?

I'd rather to this in #11

2020-05-24 07:46 UTC, maiste approved these changes

2020-05-24 07:46 UTC, merged